### ISSUE TITLE
Proposition de Roadmap

### ISSUE THREAD

**Issue by betaglop** [pia-lab/pialab-back#2]
1. Authentification/identification des acteurs
2. Gestion de rôles et permissions
3. Ajout d'un accès à une banque de modèles de registres (privative?)
4. Workflows d'intervention dans la définition des traitements du registre
5. Possibilité de limiter la PIA à tout ou partie des étapes exhaustives en fonction de choix arbitraires ou guidés (via la définition de la sensibilité des données par exemple)
6. Possibilité de déterminer des risques et des mesures à appliquer à plusieurs PIA
7. Gestion de crises
8. Gestion des demandes d'accès aux données personnelles par les personnes référencées
9. Tableau de bord personnalisé
10. Identification formelle des acteurs + sous-traitants + etc.
11. Regroupement des PIAs par traitement de référence (traçabilité)
12. Extraction de bilans généraux (aggrégation de chaque PIA, et de l'historique des évolutions)
13. Gestion réelle de calendriers
14. etc.

À compléter.

**Comment by FanchTheSystem** [comment]
Premier texte ici: https://github.com/LINCnil/pia-back/issues/29

A noter qu'il y a beaucoup de demande pour de la gestion des rôles et utilisateurs:
https://github.com/LINCnil/pia/issues/75
https://github.com/LINCnil/pia/issues/197
https://github.com/LINCnil/pia-back/issues/31
https://github.com/LINCnil/pia-app/issues/13

**Comment by FanchTheSystem** [comment]
Il y a aussi des demandes pour une installation plus facile:
https://github.com/LINCnil/pia/issues/109
https://github.com/LINCnil/pia/issues/64
Et des essais avec docker
https://github.com/LINCnil/pia-back/pull/15
https://github.com/LINCnil/pia-back/pull/12

Un début de réponse ici: https://github.com/pia-lab/pialab-docker

**Comment by GlennCavarle** [comment]
La roadmap est maintenant accessible ici : https://github.com/orgs/pia-lab/projects/1
Je ferme l'issue.
