### ISSUE TITLE
 [ERROR] Application with name Â« Default App Â» was not found

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-back#26]
Hello,

I have try to deploy pialab and i have this error:

> psql -qt --no-align -w -h 172.18.0.3 -c 'select count(*) from pia_user where email='\''api@pialab.io'\'';' -U pia_user_pialab -d pia_db_pialab
> + testuserexist=0
> + '[' 0 -eq 0 ']'
> + bin/console pia:user:create api@pialab.io api42 '--application=Default App'
> 
> [ERROR] Application with name Â« Default App Â» was not found**
> The command '/bin/sh -c git clone https://github.com/pia-lab/pialab-back.git -b ${BACKBRANCH} /usr/share/pialab-back     && cd /usr/share/pialab-back     && BUILDENV=${BUILDENV} Suffix=${NAME} CLIENTURL=${FRONTURL} ./bin/ci-scripts/set_env_with_etcd.sh     && ./bin/ci-scripts/set_pgpass.sh     && . /usr/share/pialab-back/.env     && ./bin/ci-scripts/install.sh     && ./bin/ci-scripts/create_database.sh     && psql -w -h ${DBHOST} -c "ALTER USER ${DBUSER} WITH PASSWORD '${DBPASSWORD}';" -U ${DBROOTUSER}     && ./bin/ci-scripts/create_schema.sh     && if [ "$CREATEUSER" = "true" ]; then ./bin/ci-scripts/create_user.sh; fi     && CLIENTURL=${FRONTURL} ./bin/ci-scripts/create_client_secret.sh     && ./bin/ci-scripts/update_users_app.sh     && ./bin/ci-scripts/post_install.sh' returned a non-zero code: 42>

**Comment by GlennCavarle** [comment]
Hi @GhostRock37 and thanks for reporting,
This problem has been fixed in pialab-docker with commit pia-lab/pialab-docker@0f9fd4d.
The "Default App" is now created before users.
Cheers,
