### ISSUE TITLE
User creation failed if one user is already exist with the same adresse mail

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-back#27]
Hello !

create a user by filling in an email address already filled in on a newly created userp causes a 500 error

![image](https://user-images.githubusercontent.com/25516319/42100817-8bd1263c-7bc1-11e8-8763-6dfb798839b9.png)

![image](https://user-images.githubusercontent.com/25516319/42100803-7f872cfa-7bc1-11e8-96b6-61a0ce4da3c5.png)

**Comment by RomainSanchez** [comment]
Thanks @GhostRock37. this is caused by the unique constraint on user email.We forgot to manage the error.
We'll fix it as soon as we can

**Comment by PapsOu** [comment]
Hello @GhostRock37, this PR #37 should do the trick.

It will be available for the next release.
