### ISSUE TITLE
Unable to login after last git updates

### ISSUE THREAD

**Issue by daniel84** [pia-lab/pialab-back#63]
Already added this issue on the frontend side, but probably here is more appropriate...

### Summary
After a couple of last git updates I'm not able to do login from frontend anymore.

### Steps to reproduce
Pull the code from git, make the necessary composer update, npm install and doctrine migrations, then run the server and the client. Try to login from the client.

### Expected behavior
Make a succesful login

### Actual behavior
Opening the Chrome Develper console, you can see that when the client calls the following service, it gets an error in response:
http://[host]:[port]/profile
Response: {
"code": 500,
"message": "Notice: unserialize(): Error at offset 0 of 29 bytes"
}

**Comment by PapsOu** [comment]
Hello @daniel84, I can't reproduce your bug. Can you give me informations that appears in the symfony log under `var/log/prod.log` (or `dev.log` if you're in `dev` env) ?

**Comment by daniel84** [comment]
Hello @PapsOu, you can find the dev.log from my dev env in the attached file.
It is the portion regarding the moment when I click on the Login button.
[LoginError.txt](https://github.com/pia-lab/pialab-back/files/2310220/LoginError.txt)

**Comment by PapsOu** [comment]
Could you give me more informations if you're in dev env ?

Open the profiler, search for the `GET /profile` item and go to `Exception` section. Please give me a screenshot or a text copy of the full stack.

Be sure to have you vendors sync with the `composer.lock` file (run a `composer install`). Also, please check in database that the `pia_user`, the one you try to log in with, have it's own `user_profile` entry.

**Comment by daniel84** [comment]
To be sure I've deleted the `vendor` folder and the `composer.lock` file and rerun the `composer install` command.
I also controlled the `pia_user` and `pia_profile` tables and in `pia_profile` table I have the correct `user_id` for my user...
You can find the full stacktrace of the exception from the Symfony profiler of `GET /profile` item.
[StackTrace.txt](https://github.com/pia-lab/pialab-back/files/2310889/StackTrace.txt)

**Comment by daniel84** [comment]
It was indeed a cache problem.
I deleted it and everything works now!
Thank you very much @PapsOu
